import 'package:blue_beacon/setting.dart';
import 'package:flutter/material.dart';

// void main() {
//   // runApp(TestApp());
//
//   runApp(MaterialApp(
//     home: TestApp(),
//   ));
// }

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class TestApp extends StatefulWidget {
  @override
  _TestAppState createState() => _TestAppState();
}

class _TestAppState extends State<TestApp> {
  bool isBluetoothOn = false;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        // appBar: AppBar(
        //   title: Text('아이콘 버튼 예제'),
        // ),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.spaceEvenly,
            children: [
              // IconButton(
              //   onPressed: () {
              //     // 버튼이 클릭될 때 수행할 작업을 여기에 추가
              //   },
              //   icon: Image.asset(
              //     'assets/bluetoothButton.png', // 사용할 이미지 파일 경로
              //     width: 500, // 이미지의 너비 설정
              //     height: 500, // 이미지의 높이 설정
              //   ), // 아이콘 색상 설정
              // ),
              InkWell(
                highlightColor: Colors.transparent, // 모서리로 퍼져나가는 이펙트 제거
                splashColor: Colors.transparent, // 클릭시 원형 이펙트 제거
                onTap: () {
                  setState(() {
                    isBluetoothOn = !isBluetoothOn;
                  });
                },
                child: isBluetoothOn
                    ? Image.asset(
                        "assets/image/bluetooth_on.png") // Bluetooth 켜짐 상태 이미지
                    : Image.asset(
                        "assets/image/bluetooth_off.png"), // Bluetooth 꺼짐 상태 이미지
              ),
              Row(
                crossAxisAlignment: CrossAxisAlignment.center,
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  ElevatedButton(
                    onPressed: () {},
                    child: Text("비컨 재등록", style: TextStyle(fontSize: 24)),
                  ),
                  SizedBox(width: 16),
                  ElevatedButton(
                    onPressed: () {
                      Navigator.push(context, MaterialPageRoute(builder: (context) => SettingScreen()));
                    },
                    child: const Text("알림 설정", style: TextStyle(fontSize: 24)),
                  )
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }
}
