import 'package:flutter/material.dart';

void main() {
  runApp(TestApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class TestApp extends StatefulWidget {
  @override
  _TestAppState createState() => _TestAppState();
}

class _TestAppState extends State<TestApp> {
  bool isBluetoothOn = false;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('아이콘 버튼 예제'),
        ),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              // IconButton(
              //   onPressed: () {
              //     // 버튼이 클릭될 때 수행할 작업을 여기에 추가
              //   },
              //   icon: Image.asset(
              //     'assets/bluetoothButton.png', // 사용할 이미지 파일 경로
              //     width: 500, // 이미지의 너비 설정
              //     height: 500, // 이미지의 높이 설정
              //   ), // 아이콘 색상 설정
              // ),
              InkWell(
                highlightColor: Colors.transparent, //모서리로 퍼져나가는 이펙트
                splashColor: Colors.transparent, //클릭시 원형 이펙트
                onTap: () {
                  setState(() {
                    isBluetoothOn = !isBluetoothOn;
                  });
                },
                child: isBluetoothOn
                    ? Image.asset(
                        "assets/image/bluetooth_on.png") // Bluetooth 켜짐 상태 이미지
                    : Image.asset(
                        "assets/image/bluetooth_off.png"), // Bluetooth 꺼짐 상태 이미지
              ),
              Row(
                crossAxisAlignment: CrossAxisAlignment.center,
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  ElevatedButton(
                    onPressed: () {},
                    child: Text("비컨 재등록", style: TextStyle(fontSize: 24)),
                  ) // 버튼 아래에 간격을 줍니다.
                  ,
                  ElevatedButton(
                    onPressed: () {},
                    child: Text("알림 설정", style: TextStyle(fontSize: 24)),
                  ) // 버튼 아래에 간격을 줍니다.
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }
}
